[build]
  publish = "kdman"
  command = ""
  
[[redirects]]
  from = "/"
  to = "/download.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://kduyetman.online/:splat"
  status = 301
  force = true

